# Generated by Django 3.2 on 2021-04-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
