# Generated by Django 3.2 on 2021-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientdata_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
