# Generated by Django 3.2 on 2021-04-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientdata_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='long',
            new_name='lng',
        ),
    ]
