# Generated by Django 3.2 on 2021-04-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_long_patientdata_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='notification_reg_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
