# Generated by Django 3.2 on 2021-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientdata_notification_reg_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='patient//profile//'),
        ),
    ]
