# Generated by Django 3.2 on 2021-04-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('license_no', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='WeekData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'week',
            },
        ),
        migrations.CreateModel(
            name='HospitalSpecializationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.hospitaldata')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.specializationdata')),
            ],
            options={
                'db_table': 'hospital_specialization',
            },
        ),
        migrations.CreateModel(
            name='HospitalDoctorScheduleData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.IntegerField()),
                ('visit_start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_end_time', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctordata')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.hospitaldata')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.weekdata')),
            ],
            options={
                'db_table': 'hospital_doctor_schedule',
            },
        ),
        migrations.CreateModel(
            name='HospitalDoctorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_end_time', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_start_day', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_end_day', models.CharField(blank=True, max_length=255, null=True)),
                ('room_no', models.CharField(blank=True, max_length=255, null=True)),
                ('max_patient_per_day', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctordata')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.hospitaldata')),
            ],
            options={
                'db_table': 'hospital_doctor',
            },
        ),
        migrations.CreateModel(
            name='DoctorAppointmentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_no', models.IntegerField()),
                ('visit_time', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_date', models.DateField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone', models.CharField(max_length=255)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.doctordata')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.hospitaldata')),
            ],
            options={
                'db_table': 'doctor_appointment',
                'unique_together': {('doctor', 'hospital', 'visit_date', 'patient_phone')},
            },
        ),
    ]
