# Generated by Django 3.2 on 2021-04-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctordata_specialization'),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldoctordata',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.doctordata'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctordata',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.hospitaldata'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctorscheduledata',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.doctordata'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctorscheduledata',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.hospitaldata'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctorscheduledata',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.weekdata'),
        ),
        migrations.AlterField(
            model_name='hospitalspecializationdata',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.hospitaldata'),
        ),
        migrations.AlterField(
            model_name='hospitalspecializationdata',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.specializationdata'),
        ),
    ]
