# Generated by Django 3.2 on 2021-04-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20210417_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointmentdata',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
