# Generated by Django 3.2 on 2021-04-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_doctorappointmentdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldata',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
