# Generated by Django 3.2 on 2021-04-21 14:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_hospitaldata_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldata',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/health_project_media_files/', location='/Volumes/DeepMind/Project/HealthProject/Backend-new/health_project_media_files'), upload_to='hospital'),
        ),
    ]
