# Generated by Django 3.2 on 2021-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0012_remove_hospitaldata_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldata',
            name='logo',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='hospital//profile//', width_field=100),
        ),
    ]
