# Generated by Django 3.2 on 2021-04-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0013_hospitaldata_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldata',
            name='logo',
        ),
    ]
