# Generated by Django 3.2 on 2021-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_remove_hospitaldata_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldata',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='hospital//profile//'),
        ),
    ]
