# Generated by Django 3.2 on 2021-04-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientdata_notification_reg_token'),
        ('Hospital', '0015_hospitaldata_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointmentdata',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='doctorappointmentdata',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patientdata'),
        ),
    ]
