# Generated by Django 3.2 on 2021-05-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0016_auto_20210429_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldata',
            name='lat',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldata',
            name='lng',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaldata',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hospitaldata',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
