# Generated by Django 3.2 on 2021-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0018_hospitaldata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldoctordata',
            name='max_patient_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
