# Generated by Django 3.2 on 2021-08-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0019_alter_hospitaldoctordata_max_patient_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldata',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
