# Generated by Django 3.2 on 2021-08-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0020_alter_hospitaldata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctordata',
            name='time_spent_per_patient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
