# Generated by Django 3.2 on 2021-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_doctordata_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='notification_reg_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
