# Generated by Django 3.2 on 2021-04-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_doctordata_notification_reg_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='notification_reg_token',
        ),
    ]
