# Generated by Django 3.2 on 2021-07-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_remove_doctordata_notification_reg_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
